// Mock Data with Slugs
export const MOCK_BRANDS = [
  {
    id: "1",
    slug: "ippodo",
    name: "Ippodo Tea",
    description: "Kyoto-based tea company with over 300 years of history.",
    logo_url: "https://placehold.co/400x400/171717/FFF?text=IT",
    website: "https://ippodotea.com",
    matchas_count: 12,
  },
  {
    id: "2",
    slug: "marukyu-koyamaen",
    name: "Marukyu Koyamaen",
    description: "Highly regarded tea grower and manufacturer in Uji, Kyoto.",
    logo_url: "https://placehold.co/400x400/171717/FFF?text=MK",
    website: "https://marukyu-koyamaen.co.jp",
    matchas_count: 8,
  },
  {
    id: "3",
    slug: "breakaway-matcha",
    name: "Breakaway Matcha",
    description: "Sourcing and blending the highest quality matcha from Uji.",
    logo_url: "https://placehold.co/400x400/171717/FFF?text=BM",
    website: "https://breakawaymatcha.com",
    matchas_count: 5,
  },
];

export const MOCK_PRODUCTS = [
  {
    id: "101",
    brand_id: "1",
    name: "Sayaka-no-mukashi",
    price: 35.00,
    description: "Rich umami with a smooth finish. Perfect for Koicha.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Sayaka",
    avg_rating: 4.8,
    avg_sweetness: 4.5,
    avg_bitterness: 2.0,
    avg_umami: 4.9,
    review_count: 124,
  },
  {
    id: "102",
    brand_id: "1",
    name: "Horai-no-mukashi",
    price: 28.00,
    description: "Balanced sweetness and slight astringency. Great daily drinker.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Horai",
    avg_rating: 4.5,
    avg_sweetness: 3.8,
    avg_bitterness: 2.5,
    avg_umami: 4.0,
    review_count: 89,
  },
  {
    id: "103",
    brand_id: "2",
    name: "Aoarashi",
    price: 22.00,
    description: "Approachable and vibrant green. Good for lattes.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Aoarashi",
    avg_rating: 4.2,
    avg_sweetness: 3.0,
    avg_bitterness: 3.5,
    avg_umami: 3.2,
    review_count: 210,
  },
  {
    id: "104",
    brand_id: "3",
    name: "Coldbrew Original",
    price: 45.00,
    description: "Specifically designed for cold preparation. Sweet and creamy.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Coldbrew",
    avg_rating: 4.9,
    avg_sweetness: 5.0,
    avg_bitterness: 1.0,
    avg_umami: 4.5,
    review_count: 56,
  },
];
