export const MOCK_BRANDS = [
  {
    id: "1",
    slug: "ippodo",
    name: "Ippodo Tea",
    description: "Kyoto-based tea company with over 300 years of history.",
    logo_url: "https://placehold.co/400x400/171717/FFF?text=IT",
    website: "https://ippodotea.com",
    matchas_count: 12,
  },
  {
    id: "2",
    slug: "marukyu-koyamaen",
    name: "Marukyu Koyamaen",
    description: "Highly regarded tea grower and manufacturer in Uji, Kyoto.",
    logo_url: "https://placehold.co/400x400/171717/FFF?text=MK",
    website: "https://marukyu-koyamaen.co.jp",
    matchas_count: 8,
  },
  {
    id: "3",
    slug: "naoki-matcha",
    name: "Naoki Matcha",
    description: "Creating Japanese matcha blends for modern lifestyles.",
    logo_url: "https://placehold.co/400x400/171717/FFF?text=NM",
    website: "https://naokimatcha.com",
    matchas_count: 6,
  },
  {
    id: "4",
    slug: "nakamura-tokichi",
    name: "Nakamura Tokichi",
    description: "Historic tea merchant from Uji since 1854.",
    logo_url: "https://placehold.co/400x400/171717/FFF?text=NT",
    website: "https://tokichi.jp",
    matchas_count: 10,
  },
  {
    id: "5",
    slug: "kanbayashi-shunsho",
    name: "Kanbayashi Shunsho",
    description: "Traditional tea shop with deep roots in Uji tea culture.",
    logo_url: "https://placehold.co/400x400/171717/FFF?text=KS",
    website: "https://shunsho.co.jp",
    matchas_count: 6,
  },
  {
    id: "6",
    slug: "yamamasa-koyamaen",
    name: "Yamamasa Koyamaen",
    description: "Respecting tradition while innovating in matcha production.",
    logo_url: "https://placehold.co/400x400/171717/FFF?text=YK",
    website: "https://yamamasa-koyamaen.co.jp",
    matchas_count: 8,
  },
  {
    id: "7",
    slug: "tsujiri",
    name: "Tsujiri",
    description: "Founded in 1860, famous for high quality Uji matcha.",
    logo_url: "https://placehold.co/400x400/171717/FFF?text=TJ",
    website: "https://tsujiri.co.jp",
    matchas_count: 9,
  },
  {
    id: "8",
    slug: "breakaway-matcha",
    name: "Breakaway Matcha",
    description: "Sourcing and blending the highest quality matcha from Uji.",
    logo_url: "https://placehold.co/400x400/171717/FFF?text=BM",
    website: "https://breakawaymatcha.com",
    matchas_count: 6,
  },
  {
    id: "9",
    slug: "horii-shichimeien",
    name: "Horii Shichimeien",
    description: "600 years of history. Preserving the Uji tradition.",
    logo_url: "https://placehold.co/400x400/171717/FFF?text=HS",
    website: "https://horiishichimeien.com",
    matchas_count: 6,
  },
  {
    id: "10",
    slug: "fukujuen",
    name: "Fukujuen",
    description: "Renowned Kyoto tea house known for quality and prestige.",
    logo_url: "https://placehold.co/400x400/171717/FFF?text=FJ",
    website: "https://fukujuen.com",
    matchas_count: 5,
  },
  {
    id: "11",
    slug: "hekisuien",
    name: "Hekisuien",
    description: "Historic Uji producer, supplier to Kenninji temple.",
    logo_url: "https://placehold.co/400x400/171717/FFF?text=HK",
    website: "https://hekisuien.jp",
    matchas_count: 6,
  },
  {
    id: "12",
    slug: "morihan",
    name: "Morihan",
    description: "Authentic Japanese tea from Uji since 1836.",
    logo_url: "https://placehold.co/400x400/171717/FFF?text=MH",
    website: "https://teahouse.morihan.jp",
    matchas_count: 5,
  },
];

export const MOCK_PRODUCTS = [
  {
    id: "101",
    brand_id: "1",
    name: "Sayaka-no-mukashi",
    price: 35.00,
    description: "Rich umami with a smooth finish. Perfect for Koicha.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Sayaka",
    avg_rating: 4.8,
    avg_sweetness: 4.5,
    avg_bitterness: 2.0,
    avg_umami: 4.9,
    review_count: 124,
  },
  {
    id: "102",
    brand_id: "1",
    name: "Horai-no-mukashi",
    price: 28.00,
    description: "Balanced sweetness and slight astringency. Great daily drinker.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Horai",
    avg_rating: 4.5,
    avg_sweetness: 3.8,
    avg_bitterness: 2.5,
    avg_umami: 4.0,
    review_count: 89,
  },
  {
    id: "105",
    brand_id: "1",
    name: "Ummon-no-mukashi",
    price: 55.00,
    description: "Ippodo's highest grade. Extraordinary umami and sweetness.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Ummon",
    avg_rating: 5.0,
    avg_sweetness: 5.0,
    avg_bitterness: 0.5,
    avg_umami: 5.0,
    review_count: 42,
  },
  {
    id: "106",
    brand_id: "1",
    name: "Kuon-no-mukashi",
    price: 45.00,
    description: "Robust and full-bodied. A favorite among serious practitioners.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Kuon",
    avg_rating: 4.7,
    avg_sweetness: 4.2,
    avg_bitterness: 2.8,
    avg_umami: 4.6,
    review_count: 65,
  },
  {
    id: "107",
    brand_id: "1",
    name: "Shoin-no-mukashi",
    price: 32.00,
    description: "Fresh and lively character. Excellent for Usucha.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Shoin",
    avg_rating: 4.6,
    avg_sweetness: 4.0,
    avg_bitterness: 2.2,
    avg_umami: 4.2,
    review_count: 78,
  },
  {
    id: "108",
    brand_id: "1",
    name: "Kan-no-shiro",
    price: 24.00,
    description: "Bright green color and brisk flavor. Good entry-level ceremonial.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Kan",
    avg_rating: 4.3,
    avg_sweetness: 3.2,
    avg_bitterness: 3.5,
    avg_umami: 3.5,
    review_count: 156,
  },
  {
    id: "109",
    brand_id: "1",
    name: "Hatsu-mukashi",
    price: 18.00,
    description: "Light body with a clean finish. Suitable for practice.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Hatsu",
    avg_rating: 4.0,
    avg_sweetness: 2.5,
    avg_bitterness: 4.0,
    avg_umami: 2.8,
    review_count: 92,
  },
  {
    id: "110",
    brand_id: "1",
    name: "Kimmo-no-mukashi",
    price: 20.00,
    description: "Well-rounded flavor profile. Versatile for thin tea.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Kimmo",
    avg_rating: 4.2,
    avg_sweetness: 3.0,
    avg_bitterness: 3.2,
    avg_umami: 3.3,
    review_count: 110,
  },
  {
    id: "111",
    brand_id: "1",
    name: "Yuga-no-shiro",
    price: 60.00,
    description: "Exquisite elegance and rich aroma. Limited release.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Yuga",
    avg_rating: 4.9,
    avg_sweetness: 4.8,
    avg_bitterness: 1.0,
    avg_umami: 4.8,
    review_count: 35,
  },
  {
    id: "112",
    brand_id: "1",
    name: "Seikan-no-shiro",
    price: 40.00,
    description: "Deep green color with a profound, lingering aftertaste.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Seikan",
    avg_rating: 4.6,
    avg_sweetness: 4.1,
    avg_bitterness: 2.5,
    avg_umami: 4.5,
    review_count: 55,
  },
  {
    id: "113",
    brand_id: "1",
    name: "Kuntai-no-shiro",
    price: 38.00,
    description: "Full-bodied with a slight floral note.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Kuntai",
    avg_rating: 4.5,
    avg_sweetness: 3.9,
    avg_bitterness: 2.7,
    avg_umami: 4.3,
    review_count: 62,
  },
  {
    id: "114",
    brand_id: "1",
    name: "Gokujo-hourai",
    price: 30.00,
    description: "A premium blend offering a great balance of sweet and bitter.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Gokujo",
    avg_rating: 4.4,
    avg_sweetness: 3.7,
    avg_bitterness: 3.0,
    avg_umami: 4.0,
    review_count: 70,
  },
  // Marukyu Koyamaen (8 blends)
  {
    id: "103",
    brand_id: "2",
    name: "Aoarashi",
    price: 22.00,
    description: "Approachable and vibrant green. Good for lattes.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Aoarashi",
    avg_rating: 4.2,
    avg_sweetness: 3.0,
    avg_bitterness: 3.5,
    avg_umami: 3.2,
    review_count: 210,
  },
  {
    id: "201",
    brand_id: "2",
    name: "Isuzu",
    price: 26.00,
    description: "Standard ceremonial grade. Creamy texture with pine notes.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Isuzu",
    avg_rating: 4.4,
    avg_sweetness: 3.5,
    avg_bitterness: 3.0,
    avg_umami: 3.8,
    review_count: 180,
  },
  {
    id: "202",
    brand_id: "2",
    name: "Chigi-no-shiro",
    price: 30.00,
    description: "Smooth and distinctively sweet aroma.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Chigi",
    avg_rating: 4.5,
    avg_sweetness: 4.0,
    avg_bitterness: 2.5,
    avg_umami: 4.1,
    review_count: 140,
  },
  {
    id: "203",
    brand_id: "2",
    name: "Wako",
    price: 42.00,
    description: "Premium ceremonial. Full umami and zero bitterness.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Wako",
    avg_rating: 4.8,
    avg_sweetness: 4.5,
    avg_bitterness: 1.0,
    avg_umami: 4.6,
    review_count: 95,
  },
  {
    id: "204",
    brand_id: "2",
    name: "Unkaku",
    price: 50.00,
    description: "Suitable for Koicha. Deep, savory richness.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Unkaku",
    avg_rating: 4.9,
    avg_sweetness: 4.8,
    avg_bitterness: 0.5,
    avg_umami: 5.0,
    review_count: 60,
  },
  {
    id: "205",
    brand_id: "2",
    name: "Kinrin",
    price: 38.00,
    description: "Balanced and classic Uji flavor. Very popular.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Kinrin",
    avg_rating: 4.6,
    avg_sweetness: 4.2,
    avg_bitterness: 2.0,
    avg_umami: 4.3,
    review_count: 115,
  },
  {
    id: "206",
    brand_id: "2",
    name: "Yugen",
    price: 34.00,
    description: "Elegant and subtle sweetness. Great for daily ceremony.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Yugen",
    avg_rating: 4.5,
    avg_sweetness: 3.9,
    avg_bitterness: 2.8,
    avg_umami: 4.0,
    review_count: 88,
  },
  {
    id: "207",
    brand_id: "2",
    name: "Eiju",
    price: 45.00,
    description: "Excellent aroma and bright green color.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Eiju",
    avg_rating: 4.7,
    avg_sweetness: 4.3,
    avg_bitterness: 1.8,
    avg_umami: 4.5,
    review_count: 50,
  },

  // Naoki Matcha (6 blends)
  {
    id: "104",
    brand_id: "3",
    name: "Coldbrew Original",
    price: 45.00,
    description: "Specifically designed for cold preparation. Sweet and creamy.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Coldbrew",
    avg_rating: 4.9,
    avg_sweetness: 5.0,
    avg_bitterness: 1.0,
    avg_umami: 4.5,
    review_count: 56,
  },
  {
    id: "301",
    brand_id: "3",
    name: "Fragrant Yame",
    price: 30.00,
    description: "From Yame, Fukuoka. Nutty and nutty-sweet profile.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Yame",
    avg_rating: 4.7,
    avg_sweetness: 4.2,
    avg_bitterness: 1.5,
    avg_umami: 4.2,
    review_count: 45,
  },
  {
    id: "302",
    brand_id: "3",
    name: "Superior Ceremonial",
    price: 35.00,
    description: "Uji blend. Classic balance of umami and astringency.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Superior",
    avg_rating: 4.6,
    avg_sweetness: 3.8,
    avg_bitterness: 2.5,
    avg_umami: 4.0,
    review_count: 120,
  },
  {
    id: "303",
    brand_id: "3",
    name: "Organic Ceremonial",
    price: 28.00,
    description: "Kagoshima organic matcha. Grassy and lighter body.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Organic",
    avg_rating: 4.1,
    avg_sweetness: 3.0,
    avg_bitterness: 3.8,
    avg_umami: 2.5,
    review_count: 85,
  },
  {
    id: "304",
    brand_id: "3",
    name: "First Spring Blend",
    price: 50.00,
    description: "Shincha matcha. Incredibly fresh and vibrant.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Spring",
    avg_rating: 4.8,
    avg_sweetness: 4.6,
    avg_bitterness: 1.2,
    avg_umami: 4.4,
    review_count: 30,
  },
  {
    id: "305",
    brand_id: "3",
    name: "Chiran Harvest",
    price: 26.00,
    description: "Single origin from Chiran. Bold and vegetal.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Chiran",
    avg_rating: 4.3,
    avg_sweetness: 3.2,
    avg_bitterness: 3.0,
    avg_umami: 3.0,
    review_count: 65,
  },

  // Nakamura Tokichi (10 blends) - Only adding top 3 for brevity but logic holds
  {
    id: "401",
    brand_id: "4",
    name: "Toki-no-mukashi",
    price: 65.00,
    description: "Premium Koicha grade. Velvety and rich.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Toki",
    avg_rating: 4.9,
    avg_sweetness: 5.0,
    avg_bitterness: 0.2,
    avg_umami: 5.0,
    review_count: 40,
  },
  {
    id: "402",
    brand_id: "4",
    name: "Hatsune",
    price: 32.00,
    description: "Classic Nakamura flavor. Good structure.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Hatsune",
    avg_rating: 4.5,
    avg_sweetness: 3.8,
    avg_bitterness: 2.5,
    avg_umami: 4.0,
    review_count: 90,
  },
  {
    id: "403",
    brand_id: "4",
    name: "Myo-o-no-mukashi",
    price: 45.00,
    description: "Complex and floral. Very aromatic.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Myo",
    avg_rating: 4.7,
    avg_sweetness: 4.4,
    avg_bitterness: 1.5,
    avg_umami: 4.5,
    review_count: 55,
  },
  // ... (Can add more to reach 10 later if needed)
  // ... (Previous products remain)
  
  // Nakamura Tokichi (10 blends) - Populating rest
  {
    id: "404",
    brand_id: "4",
    name: "Uji-no-shiro",
    price: 28.00,
    description: "Approachable and sweet. Perfect for newcomers.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Uji",
    avg_rating: 4.4,
    avg_sweetness: 4.0,
    avg_bitterness: 3.0,
    avg_umami: 3.8,
    review_count: 67,
  },
  {
    id: "405",
    brand_id: "4",
    name: "Gokujo",
    price: 36.00,
    description: "High quality usucha with a bright finish.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Gokujo",
    avg_rating: 4.6,
    avg_sweetness: 4.1,
    avg_bitterness: 2.2,
    avg_umami: 4.2,
    review_count: 81,
  },
   {
    id: "406",
    brand_id: "4",
    name: "Fuji-no-Shiro",
    price: 40.00,
    description: "Classic usucha with a refreshing aftertaste.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Fuji",
    avg_rating: 4.5,
    avg_sweetness: 3.8,
    avg_bitterness: 2.8,
    avg_umami: 4.0,
    review_count: 102,
  },
  {
    id: "407",
    brand_id: "4",
    name: "Senun-no-Shiro",
    price: 52.00,
    description: "Rich and creamy, suitable for special occasions.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Senun",
    avg_rating: 4.7,
    avg_sweetness: 4.4,
    avg_bitterness: 1.8,
    avg_umami: 4.5,
    review_count: 48,
  },
  {
    id: "408",
    brand_id: "4",
    name: "Hiroha-no-Shiro",
    price: 25.00,
    description: "Light and grassy, great for daily drinking.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Hiroha",
    avg_rating: 4.2,
    avg_sweetness: 3.2,
    avg_bitterness: 3.5,
    avg_umami: 3.0,
    review_count: 156,
  },
  {
    id: "409",
    brand_id: "4",
    name: "Chiye-no-Mukashi",
    price: 60.00,
    description: "Deep, complex flavor for thick tea.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Chiye",
    avg_rating: 4.8,
    avg_sweetness: 4.6,
    avg_bitterness: 1.0,
    avg_umami: 4.9,
    review_count: 35,
  },
  {
    id: "410",
    brand_id: "4",
    name: "Aoarashi", /* Note: Marukyu also uses this name, keeping for accuracy */
    price: 20.00,
    description: "Standard grade for practice and cooking.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Aoarashi",
    avg_rating: 4.0,
    avg_sweetness: 2.5,
    avg_bitterness: 4.5,
    avg_umami: 2.8,
    review_count: 200,
  },

  // Kanbayashi Shunsho (4 blends -> Added more to list)
  {
    id: "501",
    brand_id: "5",
    name: "Asahi-no-shiro",
    price: 24.00,
    description: "Light and refreshing. Traditional Uji flavor.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Asahi",
    avg_rating: 4.3,
    avg_sweetness: 3.5,
    avg_bitterness: 3.2,
    avg_umami: 3.5,
    review_count: 45,
  },
  {
    id: "502",
    brand_id: "5",
    name: "Matsu-no-shiro",
    price: 35.00,
    description: "Rich and creamy foam. A historical favorite.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Matsu",
    avg_rating: 4.6,
    avg_sweetness: 4.2,
    avg_bitterness: 2.0,
    avg_umami: 4.1,
    review_count: 60,
  },
  {
    id: "503",
    brand_id: "5",
    name: "Biwa-no-shiro",
    price: 45.00,
    description: "Deep umami with a lingering sweetness.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Biwa",
    avg_rating: 4.8,
    avg_sweetness: 4.7,
    avg_bitterness: 1.2,
    avg_umami: 4.6,
    review_count: 32,
  },
  {
    id: "504",
    brand_id: "5",
    name: "Kotobuki",
    price: 55.00,
    description: "Ceremonial masterpiece. Complex layers of flavor.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Kotobuki",
    avg_rating: 4.9,
    avg_sweetness: 4.9,
    avg_bitterness: 0.8,
    avg_umami: 4.9,
    review_count: 25,
  },
  // Adding discovered
  {
    id: "505",
    brand_id: "5",
    name: "Ato Mukashi",
    price: 65.00,
    description: "Exquisite koicha grade. Velvety texture.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Ato",
    avg_rating: 4.9,
    avg_sweetness: 4.8,
    avg_bitterness: 0.5,
    avg_umami: 5.0,
    review_count: 18,
  },
  {
    id: "506",
    brand_id: "5",
    name: "Aya no Mori",
    price: 28.00,
    description: "Vibrant green with a sharp, refreshing finish.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Aya",
    avg_rating: 4.4,
    avg_sweetness: 3.5,
    avg_bitterness: 3.5,
    avg_umami: 3.8,
    review_count: 55,
  },

  // Yamamasa Koyamaen (7 blends -> Updated names)
  {
    id: "601",
    brand_id: "6",
    name: "Ogurayama",
    price: 25.00,
    description: "Best seller. Well balanced for everyday drinking.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Ogura",
    avg_rating: 4.4,
    avg_sweetness: 3.8,
    avg_bitterness: 2.8,
    avg_umami: 3.9,
    review_count: 150,
  },
  {
    id: "602",
    brand_id: "6",
    name: "Sayama-no-mukashi",
    price: 32.00,
    description: "Rich aroma and vibrant color.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Sayama",
    avg_rating: 4.5,
    avg_sweetness: 4.0,
    avg_bitterness: 2.5,
    avg_umami: 4.2,
    review_count: 85,
  },
  {
    id: "603",
    brand_id: "6",
    name: "Tennozan",
    price: 48.00,
    description: "Named after Mt. Tenno. Robust and powerful.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Tenno",
    avg_rating: 4.8,
    avg_sweetness: 4.6,
    avg_bitterness: 1.5,
    avg_umami: 4.8,
    review_count: 40,
  },
  {
    id: "604",
    brand_id: "6",
    name: "Chajyu-no-mukashi", // Replaced Ganko
    price: 60.00,
    description: "Premium koicha. Deep, resonant flavor.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Chajyu",
    avg_rating: 4.9,
    avg_sweetness: 4.8,
    avg_bitterness: 0.5,
    avg_umami: 4.9,
    review_count: 22,
  },
  {
    id: "605",
    brand_id: "6",
    name: "Matsukaze",
    price: 36.00,
    description: "Elegant and breezy. Light floral notes.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Matsu",
    avg_rating: 4.6,
    avg_sweetness: 4.2,
    avg_bitterness: 2.0,
    avg_umami: 4.3,
    review_count: 65,
  },
  {
    id: "606",
    brand_id: "6",
    name: "Choan",
    price: 55.00,
    description: "Deep relaxation in a bowl. Iconic Yamamasa blend.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Choan",
    avg_rating: 4.9,
    avg_sweetness: 4.8,
    avg_bitterness: 1.0,
    avg_umami: 4.7,
    review_count: 30,
  },
  {
    id: "607",
    brand_id: "6",
    name: "Samidare",
    price: 28.00,
    description: "Like early summer rain. Refreshing and clean.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Sami",
    avg_rating: 4.3,
    avg_sweetness: 3.6,
    avg_bitterness: 3.1,
    avg_umami: 3.8,
    review_count: 90,
  },
  {
    id: "608",
    brand_id: "6",
    name: "Yomo-no-kaori",
    price: 30.00,
    description: "Distinctive fragrance, reminiscent of spring fields.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Yomo",
    avg_rating: 4.4,
    avg_sweetness: 3.7,
    avg_bitterness: 3.0,
    avg_umami: 3.8,
    review_count: 65,
  },

  // Tsujiri (9 blends -> Updated names)
  {
    id: "701",
    brand_id: "7",
    name: "Uji Hikari",
    price: 30.00,
    description: "The light of Uji. Bright and joyful.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Hikari",
    avg_rating: 4.5,
    avg_sweetness: 4.0,
    avg_bitterness: 2.8,
    avg_umami: 4.1,
    review_count: 110,
  },
  {
    id: "702",
    brand_id: "7",
    name: "Kyo Mukashi", // Replaced Special
    price: 45.00,
    description: "Traditional Kyoto flavor. Rich and smooth.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Kyo",
    avg_rating: 4.7,
    avg_sweetness: 4.3,
    avg_bitterness: 2.0,
    avg_umami: 4.5,
    review_count: 85,
  },
  {
    id: "703",
    brand_id: "7",
    name: "Miyako-no-shiro",
    price: 22.00,
    description: "Accessible and sweet. Great for beginners.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Miyako",
    avg_rating: 4.2,
    avg_sweetness: 3.8,
    avg_bitterness: 3.2,
    avg_umami: 3.5,
    review_count: 140,
  },
  {
    id: "704",
    brand_id: "7",
    name: "Sakae no Shiro", // Replaced Morning
    price: 28.00,
    description: "Glorious white. A balanced usucha.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Sakae",
    avg_rating: 4.4,
    avg_sweetness: 3.5,
    avg_bitterness: 3.5,
    avg_umami: 3.9,
    review_count: 95,
  },
  {
    id: "705",
    brand_id: "7",
    name: "Uji Strong",
    price: 35.00,
    description: "For those who love the bitter bite of matcha.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Strong",
    avg_rating: 4.3,
    avg_sweetness: 2.0,
    avg_bitterness: 5.0,
    avg_umami: 4.0,
    review_count: 60,
  },
  {
    id: "706",
    brand_id: "7",
    name: "Premium Select",
    price: 55.00,
    description: "Hand-picked leaves. Very limited quantity.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Premium",
    avg_rating: 4.9,
    avg_sweetness: 4.8,
    avg_bitterness: 0.8,
    avg_umami: 4.9,
    review_count: 25,
  },
  {
    id: "707",
    brand_id: "7",
    name: "Sencha Match",
    price: 18.00,
    description: "Matcha blended with sencha powder.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Sencha",
    avg_rating: 4.0,
    avg_sweetness: 3.0,
    avg_bitterness: 4.0,
    avg_umami: 3.0,
    review_count: 50,
  },
  {
    id: "708",
    brand_id: "7",
    name: "Sakura Blend",
    price: 32.00,
    description: "Available only in spring. Floral finish.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Sakura",
    avg_rating: 4.6,
    avg_sweetness: 4.5,
    avg_bitterness: 2.0,
    avg_umami: 4.0,
    review_count: 120,
  },
  {
    id: "709",
    brand_id: "7",
    name: "Gold Dust",
    price: 45.00,
    description: "Contains edible gold flakes. Festive and mild.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Gold",
    avg_rating: 4.5,
    avg_sweetness: 4.0,
    avg_bitterness: 2.5,
    avg_umami: 4.0,
    review_count: 40,
  },

  // Breakaway Matcha (5 blends -> Updated names)
  {
    id: "801",
    brand_id: "8",
    name: "Blend 93",
    price: 45.00,
    description: "Top of the line organic. Impossibly smooth.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=93",
    avg_rating: 4.7,
    avg_sweetness: 4.5,
    avg_bitterness: 1.5,
    avg_umami: 4.5,
    review_count: 60,
  },
  {
    id: "802",
    brand_id: "8",
    name: "Blend 94",
    price: 55.00,
    description: "Hyperpremium. Intense umami bomb.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=94",
    avg_rating: 4.9,
    avg_sweetness: 4.8,
    avg_bitterness: 0.5,
    avg_umami: 5.0,
    review_count: 40,
  },
  {
    id: "803",
    brand_id: "8",
    name: "Coldbrew Reserve",
    price: 38.00,
    description: "Engineered for ice water. No whisk needed.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Reserve",
    avg_rating: 4.6,
    avg_sweetness: 4.4,
    avg_bitterness: 1.0,
    avg_umami: 4.3,
    review_count: 75,
  },
  {
    id: "804",
    brand_id: "8",
    name: "Blend Rikyu", /* Replaced Daily Ritual */
    price: 49.00,
    description: "Named after the master. Deep and contemplative.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Rikyu",
    avg_rating: 4.8,
    avg_sweetness: 4.0,
    avg_bitterness: 1.0,
    avg_umami: 4.8,
    review_count: 45,
  },
  {
    id: "805",
    brand_id: "8",
    name: "Blend Daphne", /* Replaced Barista Blend */
    price: 35.00,
    description: "Floral and light. A favorite for afternoon tea.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Daphne",
    avg_rating: 4.5,
    avg_sweetness: 3.5,
    avg_bitterness: 2.0,
    avg_umami: 3.8,
    review_count: 150,
  },
  {
    id: "806",
    brand_id: "8",
    name: "Blend Jizo",
    price: 32.00,
    description: "Earthy and grounded. Good structure.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Jizo",
    avg_rating: 4.4,
    avg_sweetness: 3.0,
    avg_bitterness: 3.0,
    avg_umami: 4.0,
    review_count: 65,
  },

  // Horii Shichimeien (6 blends)
  {
    id: "901",
    brand_id: "9",
    name: "Narino",
    price: 35.00,
    description: "Single origin from the famous Narino garden. Unique floral character.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Narino",
    avg_rating: 4.9,
    avg_sweetness: 4.8,
    avg_bitterness: 1.0,
    avg_umami: 4.8,
    review_count: 120,
  },
  {
    id: "902",
    brand_id: "9",
    name: "Homare no Mukashi",
    price: 45.00,
    description: "Rich and creamy. A classic premium koicha.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Homare",
    avg_rating: 4.8,
    avg_sweetness: 4.6,
    avg_bitterness: 1.5,
    avg_umami: 4.7,
    review_count: 85,
  },
  {
    id: "903",
    brand_id: "9",
    name: "Shichimei no Mukashi",
    price: 28.00,
    description: "The house signature blend. Balanced for daily use.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Shich",
    avg_rating: 4.5,
    avg_sweetness: 4.0,
    avg_bitterness: 2.8,
    avg_umami: 4.2,
    review_count: 150,
  },
  {
    id: "904",
    brand_id: "9",
    name: "Mumon",
    price: 55.00,
    description: "Top grade. Profound depth and sweetness.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Mumon",
    avg_rating: 5.0,
    avg_sweetness: 5.0,
    avg_bitterness: 0.5,
    avg_umami: 5.0,
    review_count: 30,
  },
  {
    id: "905",
    brand_id: "9",
    name: "Uji Mukashi",
    price: 22.00,
    description: "Standard high quality usucha. Refreshing.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Uji",
    avg_rating: 4.2,
    avg_sweetness: 3.2,
    avg_bitterness: 3.5,
    avg_umami: 3.5,
    review_count: 90,
  },
  {
    id: "906",
    brand_id: "9",
    name: "Agata no Shiro",
    price: 18.00,
    description: "Light and crisp. Perfect for tea lattes too.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Agata",
    avg_rating: 4.0,
    avg_sweetness: 3.0,
    avg_bitterness: 4.0,
    avg_umami: 3.0,
    review_count: 110,
  },

  // Fukujuen (5 blends)
  {
    id: "1001",
    brand_id: "10",
    name: "Banjo-no-Mukashi",
    price: 60.00,
    description: "Extraordinary quality used for ceremonies.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Banjo",
    avg_rating: 4.9,
    avg_sweetness: 4.8,
    avg_bitterness: 0.8,
    avg_umami: 4.9,
    review_count: 45,
  },
  {
    id: "1002",
    brand_id: "10",
    name: "Zuien",
    price: 40.00,
    description: "Elegant and sophisticated aroma.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Zuien",
    avg_rating: 4.7,
    avg_sweetness: 4.5,
    avg_bitterness: 2.0,
    avg_umami: 4.5,
    review_count: 70,
  },
  {
    id: "1003",
    brand_id: "10",
    name: "Kotobuki-no-Shiro",
    price: 30.00,
    description: "Bright green color with a mild sweetness.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Kotobuki",
    avg_rating: 4.4,
    avg_sweetness: 4.0,
    avg_bitterness: 2.5,
    avg_umami: 4.0,
    review_count: 120,
  },
  {
    id: "1004",
    brand_id: "10",
    name: "Seiyou-no-Shiro",
    price: 24.00,
    description: "Very accessible daily matcha.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Seiyou",
    avg_rating: 4.2,
    avg_sweetness: 3.5,
    avg_bitterness: 3.0,
    avg_umami: 3.5,
    review_count: 90,
  },
  {
    id: "1005",
    brand_id: "10",
    name: "Eisho-no-Mukashi",
    price: 50.00,
    description: "Rich distinct umami. Full bodied.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Eisho",
    avg_rating: 4.8,
    avg_sweetness: 4.5,
    avg_bitterness: 1.5,
    avg_umami: 4.7,
    review_count: 55,
  },

  // Hekisuien (6 blends)
  {
    id: "1101",
    brand_id: "11",
    name: "Chiyo-no-Sakae",
    price: 45.00,
    description: "Flagship blend. Very popular in tea circles.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Chiyo",
    avg_rating: 4.7,
    avg_sweetness: 4.4,
    avg_bitterness: 2.0,
    avg_umami: 4.6,
    review_count: 130,
  },
  {
    id: "1102",
    brand_id: "11",
    name: "Kin-no-Uzu",
    price: 32.00,
    description: "Golden Vortex. Intense flavor.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Kin",
    avg_rating: 4.4,
    avg_sweetness: 3.8,
    avg_bitterness: 3.0,
    avg_umami: 4.1,
    review_count: 95,
  },
  {
    id: "1103",
    brand_id: "11",
    name: "Hatsumukashi",
    price: 22.00,
    description: "Classic beginner friendly matcha.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Hatsu",
    avg_rating: 4.2,
    avg_sweetness: 3.2,
    avg_bitterness: 3.5,
    avg_umami: 3.5,
    review_count: 110,
  },
  {
    id: "1104",
    brand_id: "11",
    name: "Matsu-no-Midori",
    price: 28.00,
    description: "Pine green. Fresh and vegetal.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Matsu",
    avg_rating: 4.3,
    avg_sweetness: 3.6,
    avg_bitterness: 3.1,
    avg_umami: 3.8,
    review_count: 80,
  },
  {
    id: "1105",
    brand_id: "11",
    name: "Houju",
    price: 55.00,
    description: "Treasure Jewel. Exceptional sweetness.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Houju",
    avg_rating: 4.9,
    avg_sweetness: 4.9,
    avg_bitterness: 0.5,
    avg_umami: 4.8,
    review_count: 40,
  },
  {
    id: "1106",
    brand_id: "11",
    name: "Zuise no Mukashi",
    price: 48.00,
    description: "Auspicious age. Deep wisdom in a cup.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Zuise",
    avg_rating: 4.7,
    avg_sweetness: 4.5,
    avg_bitterness: 1.5,
    avg_umami: 4.6,
    review_count: 35,
  },

  // Morihan (5 blends)
  {
    id: "1201",
    brand_id: "12",
    name: "Ogura no Mukashi",
    price: 35.00,
    description: "Traditional taste of Ogura. Rich and savory.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Ogura",
    avg_rating: 4.6,
    avg_sweetness: 4.2,
    avg_bitterness: 2.2,
    avg_umami: 4.4,
    review_count: 75,
  },
  {
    id: "1202",
    brand_id: "12",
    name: "Unryu",
    price: 45.00,
    description: "Cloud Dragon. Strong and bold impression.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Unryu",
    avg_rating: 4.7,
    avg_sweetness: 4.3,
    avg_bitterness: 2.0,
    avg_umami: 4.5,
    review_count: 60,
  },
  {
    id: "1203",
    brand_id: "12",
    name: "Matsu no Sono",
    price: 25.00,
    description: "Pine Garden. Good balance for usucha.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Matsu",
    avg_rating: 4.3,
    avg_sweetness: 3.5,
    avg_bitterness: 3.0,
    avg_umami: 3.8,
    review_count: 100,
  },
  {
    id: "1204",
    brand_id: "12",
    name: "Wa Kei",
    price: 20.00,
    description: "Harmony and Respect. Great daily drinker.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=WaKei",
    avg_rating: 4.1,
    avg_sweetness: 3.0,
    avg_bitterness: 3.5,
    avg_umami: 3.2,
    review_count: 150,
  },
  {
    id: "1205",
    brand_id: "12",
    name: "Premium Organic",
    price: 30.00,
    description: "High quality JAS certified organic matcha.",
    image_url: "https://placehold.co/600x600/14532d/FFF?text=Organic",
    avg_rating: 4.4,
    avg_sweetness: 3.8,
    avg_bitterness: 3.2,
    avg_umami: 3.5,
    review_count: 110,
  },
];
